import type { Article, Section } from '@/types/database'

const now = new Date().toISOString()

export const mockArticles: Article[] = [
  // ── AI 영상 ──────────────────────────────────────────────────
  {
    id: '1', slug: 'sora-4k-update-2026',
    title_ko: 'OpenAI Sora, 4K 영상 생성 업데이트 — 실사 수준 퀄리티 달성',
    title_en: 'OpenAI Sora Updates to 4K Generation — Photorealistic Quality Achieved',
    summary: 'OpenAI가 텍스트-영상 AI Sora의 대규모 업데이트를 발표했다. 최대 4K 해상도 생성이 가능해졌으며 실사에 가까운 퀄리티를 구현했다.',
    content: null, section: 'ai-video', source_url: 'https://openai.com/sora', source_name: 'OpenAI Blog',
    image_url: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?w=1200&q=80',
    ai_generated: true, is_featured: true, is_breaking: true, view_count: 8420,
    tags: ['Sora', 'OpenAI', '영상생성', '4K'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '2', slug: 'runway-gen3-hollywood-deal',
    title_ko: 'Runway Gen-3 Alpha, 할리우드 스튜디오와 파트너십 체결',
    title_en: 'Runway Gen-3 Alpha Signs Partnership with Hollywood Studios',
    summary: 'AI 영상 생성 스타트업 Runway가 주요 할리우드 스튜디오와 Gen-3 Alpha 기술 협업 계약을 체결했다.',
    content: null, section: 'ai-video', source_url: 'https://runwayml.com', source_name: 'Runway Blog',
    image_url: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 3210,
    tags: ['Runway', 'Gen-3', '할리우드'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '3', slug: 'kling-video-ai-korea-2026',
    title_ko: 'Kling AI, 한국어 프롬프트 지원 — 국내 크리에이터 반응 폭발적',
    title_en: 'Kling AI Adds Korean Prompt Support — Explosive Response from Korean Creators',
    summary: '중국 AI 스타트업 Kuaishou의 영상 생성 AI Kling이 한국어 프롬프트를 공식 지원하기 시작했다.',
    content: null, section: 'ai-video', source_url: 'https://kling.kuaishou.com', source_name: 'Kling AI',
    image_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 2180,
    tags: ['Kling', 'Kuaishou', '영상AI'], published_at: now, created_at: now, updated_at: now,
  },
  // ── AI 의료 ──────────────────────────────────────────────────
  {
    id: '4', slug: 'fda-ai-cancer-diagnostic-2026',
    title_ko: 'FDA, AI 기반 암 조기 진단 알고리즘 3종 승인 — 정확도 97%',
    title_en: 'FDA Approves 3 AI Cancer Diagnostic Algorithms with 97% Accuracy',
    summary: 'FDA가 AI 기반 암 조기 진단 알고리즘 3종을 공식 승인했다. 임상시험에서 97%의 정확도를 달성한 것으로 확인됐다.',
    content: null, section: 'ai-medical', source_url: 'https://www.fda.gov', source_name: 'FDA',
    image_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80',
    ai_generated: true, is_featured: true, is_breaking: false, view_count: 11200,
    tags: ['FDA', 'AI의료', '암진단', '승인'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '5', slug: 'deepmind-alphafold3-record',
    title_ko: 'Google DeepMind, AlphaFold3로 단백질 예측 정확도 신기록 경신',
    title_en: 'Google DeepMind Sets New Protein Folding Accuracy Record with AlphaFold3',
    summary: 'Google DeepMind가 AlphaFold3를 통해 단백질 구조 예측에서 역대 최고 정확도를 기록했다. 신약 개발 혁명이 예고된다.',
    content: null, section: 'ai-medical', source_url: 'https://deepmind.google', source_name: 'Google DeepMind',
    image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 7830,
    tags: ['DeepMind', 'AlphaFold3', '신약개발'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '6', slug: 'ai-mental-health-therapy-2026',
    title_ko: 'AI 정신건강 상담 앱, 미국 보험 적용 첫 사례 등장',
    title_en: 'AI Mental Health App Becomes First to Gain US Insurance Coverage',
    summary: 'AI 기반 정신건강 상담 플랫폼이 미국 메이저 보험사의 보험 적용을 받는 첫 사례가 등장했다.',
    content: null, section: 'ai-medical', source_url: 'https://woebothealth.com', source_name: 'Woebot Health',
    image_url: 'https://images.unsplash.com/photo-1573497620053-ea5300f94f21?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 4560,
    tags: ['정신건강', 'AI상담', '보험'], published_at: now, created_at: now, updated_at: now,
  },
  // ── AI 법률 ──────────────────────────────────────────────────
  {
    id: '7', slug: 'eu-ai-act-regulations-2026',
    title_ko: 'EU AI Act 세부 규정 발표 — 고위험 AI 시스템 의무화 조항 확정',
    title_en: 'EU AI Act Regulations Released — High-Risk AI Requirements Finalized',
    summary: 'EU가 AI Act의 세부 구현 규정을 발표했다. 고위험 AI 시스템에 대한 의무 요건이 확정되며 기업들의 대응이 촉구된다.',
    content: null, section: 'ai-legal', source_url: 'https://digital-strategy.ec.europa.eu', source_name: 'European Commission',
    image_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&q=80',
    ai_generated: true, is_featured: true, is_breaking: false, view_count: 9870,
    tags: ['EU AI Act', 'AI규제', 'LegalTech'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '8', slug: 'ai-copyright-lawsuit-update-2026',
    title_ko: 'AI 저작권 소송 업데이트 — 미국 연방법원, 학습 데이터 사용 판단',
    title_en: 'AI Copyright Lawsuit Update — US Federal Court Rules on Training Data',
    summary: '미국 연방법원이 AI 모델 학습 데이터 사용에 관한 저작권 소송에서 중요한 중간 판결을 내렸다.',
    content: null, section: 'ai-legal', source_url: 'https://www.courtlistener.com', source_name: 'CourtListener',
    image_url: 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 6540,
    tags: ['저작권', 'AI소송', '공정이용'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '9', slug: 'korea-ai-law-amendment-2026',
    title_ko: '한국 AI 기본법 개정안 국회 통과 — 국내 AI 기업 규제 기준 확정',
    title_en: 'Korea AI Framework Law Amendment Passes National Assembly',
    summary: '대한민국 국회가 AI 기본법 개정안을 통과시켰다. 국내 AI 기업에 대한 구체적인 규제 기준이 확정됐다.',
    content: null, section: 'ai-legal', source_url: 'https://www.assembly.go.kr', source_name: '국회',
    image_url: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 5120,
    tags: ['한국AI법', 'AI기본법', '국회'], published_at: now, created_at: now, updated_at: now,
  },
  // ── AI 신규 소프트웨어 ────────────────────────────────────────
  {
    id: '10', slug: 'claude-4-launch-2026',
    title_ko: 'Anthropic Claude 4 공식 출시 — 멀티모달 추론 능력 획기적 향상',
    title_en: 'Anthropic Officially Launches Claude 4 — Multimodal Reasoning Dramatically Improved',
    summary: 'Anthropic이 Claude 4를 공식 출시했다. 이미지, 오디오, 코드 처리 능력이 크게 향상됐으며 기업용 API도 함께 공개됐다.',
    content: null, section: 'ai-software', source_url: 'https://anthropic.com/claude', source_name: 'Anthropic',
    image_url: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80',
    ai_generated: true, is_featured: true, is_breaking: true, view_count: 18500,
    tags: ['Anthropic', 'Claude4', '출시', 'LLM'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '11', slug: 'meta-llama4-open-source',
    title_ko: 'Meta, Llama 4 오픈소스 공개 — 상업적 무료 사용 허용',
    title_en: 'Meta Releases Llama 4 Open Source — Free for Commercial Use',
    summary: 'Meta가 Llama 4 모델을 오픈소스로 공개했다. 상업적 사용도 무료로 허용돼 AI 민주화에 한 발짝 더 다가섰다.',
    content: null, section: 'ai-software', source_url: 'https://ai.meta.com/llama', source_name: 'Meta AI',
    image_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80',
    ai_generated: true, is_featured: true, is_breaking: false, view_count: 15200,
    tags: ['Meta', 'Llama4', '오픈소스', 'LLM'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '12', slug: 'google-gemini-2-ultra-update',
    title_ko: 'Google Gemini 2 Ultra, 코딩 능력 1위 달성 — 개발자 도구 강화',
    title_en: 'Google Gemini 2 Ultra Tops Coding Benchmark — Developer Tools Enhanced',
    summary: 'Google이 Gemini 2 Ultra의 업데이트를 발표했다. 코딩 능력 벤치마크에서 1위를 달성하며 개발자 생태계 공략에 나섰다.',
    content: null, section: 'ai-software', source_url: 'https://gemini.google.com', source_name: 'Google DeepMind',
    image_url: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 9340,
    tags: ['Google', 'Gemini2', '코딩AI'], published_at: now, created_at: now, updated_at: now,
  },
  // ── AI 기기 ──────────────────────────────────────────────────
  {
    id: '13', slug: 'samsung-galaxy-s25-ultra-ai-benchmark',
    title_ko: 'Samsung Galaxy S25 Ultra, 온디바이스 AI 성능 벤치마크 1위 기록',
    title_en: 'Samsung Galaxy S25 Ultra Takes Top Spot in On-Device AI Benchmark',
    summary: 'Samsung의 Galaxy S25 Ultra가 온디바이스 AI 성능 벤치마크에서 1위를 차지했다.',
    content: null, section: 'ai-devices', source_url: 'https://samsung.com', source_name: 'Samsung Newsroom',
    image_url: 'https://images.unsplash.com/photo-1598327105854-4a4a62ab3cd8?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 6730,
    tags: ['Samsung', 'GalaxyS25', '온디바이스AI'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '14', slug: 'apple-vision-pro-2-ai-update',
    title_ko: 'Apple Vision Pro 2 AI 기능 업데이트 — 공간 컴퓨팅의 새 차원',
    title_en: 'Apple Vision Pro 2 AI Feature Update — New Dimension of Spatial Computing',
    summary: 'Apple이 Vision Pro 2의 AI 기능 대규모 업데이트를 공개했다. 공간 인식 AI와 실시간 번역 기능이 추가됐다.',
    content: null, section: 'ai-devices', source_url: 'https://apple.com', source_name: 'Apple',
    image_url: 'https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 5890,
    tags: ['Apple', 'VisionPro', '공간컴퓨팅'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '15', slug: 'humane-ai-pin-2-launch',
    title_ko: 'Humane AI Pin 2세대 출시 — 스마트폰 없이 AI 비서 완성',
    title_en: 'Humane AI Pin 2nd Gen Launches — Complete AI Assistant Without Smartphone',
    summary: 'Humane이 AI Pin 2세대를 공개했다. 배터리 수명과 응답 속도를 대폭 개선해 스마트폰 대체 가능성을 높였다.',
    content: null, section: 'ai-devices', source_url: 'https://humane.com', source_name: 'Humane',
    image_url: 'https://images.unsplash.com/photo-1508614999368-9260051292e5?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 4120,
    tags: ['Humane', 'AIPin', '웨어러블'], published_at: now, created_at: now, updated_at: now,
  },
  // ── AI 기업/투자 ──────────────────────────────────────────────
  {
    id: '16', slug: 'openai-300b-valuation-2026',
    title_ko: 'OpenAI 기업가치 $3,000억 돌파 — 역대 최대 VC 펀딩 완료',
    title_en: 'OpenAI Surpasses $300B Valuation — Largest Ever VC Funding Completed',
    summary: 'OpenAI가 최신 펀딩 라운드를 완료하며 기업가치 3,000억 달러를 돌파했다. AI 업계 역대 최고 밸류에이션이다.',
    content: null, section: 'ai-business', source_url: 'https://openai.com', source_name: 'OpenAI',
    image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&q=80',
    ai_generated: true, is_featured: true, is_breaking: false, view_count: 21000,
    tags: ['OpenAI', '투자', '기업가치', 'VC'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '17', slug: 'anthropic-series-e-2026',
    title_ko: 'Anthropic, Series E 100억 달러 유치 — Google·Amazon 추가 투자',
    title_en: 'Anthropic Raises $10B Series E — Google and Amazon Lead Follow-On',
    summary: 'Anthropic이 구글과 아마존이 주도하는 Series E 라운드에서 100억 달러를 유치했다.',
    content: null, section: 'ai-business', source_url: 'https://anthropic.com', source_name: 'Anthropic',
    image_url: 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 12300,
    tags: ['Anthropic', '투자', 'SeriesE'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '18', slug: 'korea-ai-startup-investment-2026',
    title_ko: '한국 AI 스타트업 2025 투자 결산 — 총 3조 원 사상 최대 기록',
    title_en: 'Korean AI Startup Investment 2025 Summary — Record 3 Trillion KRW',
    summary: '2025년 한국 AI 스타트업 투자가 사상 최대인 3조 원을 돌파했다. AI 바이오, AI 제조, AI 교육 분야에 투자 집중.',
    content: null, section: 'ai-business', source_url: 'https://www.mss.go.kr', source_name: '중소벤처기업부',
    image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 8970,
    tags: ['한국스타트업', 'AI투자', 'VC'], published_at: now, created_at: now, updated_at: now,
  },
  // ── 한인 AI 비즈니스 ──────────────────────────────────────────
  {
    id: '19', slug: 'la-koreatown-ai-hub-open',
    title_ko: 'LA 한인타운 AI 스타트업 허브 그랜드 오픈 — 10개사 첫 입주',
    title_en: 'LA Koreatown AI Startup Hub Grand Opens — 10 Companies Move In',
    summary: 'LA 한인타운에 AI 전문 스타트업 허브 "KAI Hub"가 오픈했다. 10개의 한인 AI 스타트업이 첫 입주자로 확정됐다.',
    content: null, section: 'korean-ai', source_url: 'https://kaihub.la', source_name: 'KAI Hub',
    image_url: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&q=80',
    ai_generated: true, is_featured: true, is_breaking: false, view_count: 5430,
    tags: ['LA한인타운', 'KAIHub', 'AI스타트업'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '20', slug: 'kai-network-silicon-valley-5000',
    title_ko: '실리콘밸리 한인 AI 개발자 네트워크 "KAI" 창립 — 회원 5,000명 돌파',
    title_en: 'Silicon Valley Korean AI Developer Network "KAI" Founded — 5,000 Members',
    summary: '실리콘밸리에서 한인 AI 개발자 네트워크 KAI가 창립됐다. 창립 한 달 만에 5,000명을 모집했다.',
    content: null, section: 'korean-ai', source_url: 'https://kainetwork.us', source_name: 'KAI Network',
    image_url: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&q=80',
    ai_generated: true, is_featured: true, is_breaking: false, view_count: 4210,
    tags: ['실리콘밸리', '한인개발자', 'KAI'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '21', slug: 'korean-ai-startup-y-combinator-2026',
    title_ko: '한인 AI 스타트업 4곳, YC 2026 봄 배치 동시 선발',
    title_en: '4 Korean-Founded AI Startups Selected for YC Spring 2026 Batch',
    summary: 'Y Combinator 2026 봄 배치에 한인 창업자가 설립한 AI 스타트업 4곳이 동시에 선발됐다. 역대 최다 기록이다.',
    content: null, section: 'korean-ai', source_url: 'https://ycombinator.com', source_name: 'Y Combinator',
    image_url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 7890,
    tags: ['YC', 'Y컴비네이터', '한인스타트업'], published_at: now, created_at: now, updated_at: now,
  },
  // ── AI 가이드 ──────────────────────────────────────────────────
  {
    id: '22', slug: 'chatgpt-prompt-engineering-complete-guide-ko',
    title_ko: '[완전 가이드] ChatGPT 프롬프트 엔지니어링 A to Z — 한국어 버전',
    title_en: '[Complete Guide] ChatGPT Prompt Engineering A to Z — Korean Edition',
    summary: '한국어 사용자를 위한 ChatGPT 프롬프트 엔지니어링 완전 가이드. 기초부터 고급 기법까지 단계별로 설명한다.',
    content: null, section: 'ai-guide', source_url: null, source_name: 'AI Live Now Editorial',
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&q=80',
    ai_generated: true, is_featured: true, is_breaking: false, view_count: 24500,
    tags: ['ChatGPT', '프롬프트엔지니어링', '튜토리얼'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '23', slug: 'claude-api-korean-beginner-guide',
    title_ko: '[입문] Claude API로 한국어 AI 앱 만들기 — 30분 완성',
    title_en: '[Beginner] Build a Korean AI App with Claude API in 30 Minutes',
    summary: 'Anthropic Claude API를 사용해 한국어 AI 애플리케이션을 만드는 입문 튜토리얼. 코딩 경험이 없어도 따라할 수 있다.',
    content: null, section: 'ai-guide', source_url: 'https://docs.anthropic.com', source_name: 'Anthropic Docs',
    image_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 16800,
    tags: ['Claude', 'API', '튜토리얼', 'Python'], published_at: now, created_at: now, updated_at: now,
  },
  {
    id: '24', slug: 'local-llm-ollama-korean-guide',
    title_ko: '[가이드] Ollama로 내 PC에서 LLM 돌리기 — 개인정보 걱정 없는 로컬 AI',
    title_en: '[Guide] Run LLM on Your PC with Ollama — Private Local AI',
    summary: 'Ollama를 사용해 개인 PC에서 LLM을 무료로 실행하는 방법. 인터넷 연결 없이도 AI를 사용할 수 있다.',
    content: null, section: 'ai-guide', source_url: 'https://ollama.com', source_name: 'Ollama',
    image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&q=80',
    ai_generated: true, is_featured: false, is_breaking: false, view_count: 19200,
    tags: ['Ollama', '로컬LLM', 'EXAONE', '오픈소스'], published_at: now, created_at: now, updated_at: now,
  },
]

export const getBySection = (section: Section) => mockArticles.filter(a => a.section === section)
export const getFeatured = () => mockArticles.filter(a => a.is_featured)
export const getBreaking = () => mockArticles.filter(a => a.is_breaking)
export const getTrending = () => [...mockArticles].sort((a, b) => b.view_count - a.view_count).slice(0, 5)
export const getLatest = () => [...mockArticles].sort((a, b) => new Date(b.published_at).getTime() - new Date(a.published_at).getTime()).slice(0, 5)
export const getBySlug = (slug: string) => mockArticles.find(a => a.slug === slug)
